### Sign in first to get the cookie
POST http://localhost:3000/signin
Content-Type: application/json

{
    "email": "kimjong@gmail.com",
    "password": "John@123"
}

###

### Create blog (requires signin cookie)
POST http://localhost:3000/create-blog
Content-Type: application/json

{
    "title":"test title",
    "banner": "https://example.com/image-url",
    "description":"short description text",
    "content":{
        "blocks":[1,2,3]
    },
    "tags":["tag1", "tag two"]
}

###

### Add comment (requires signin cookie)
POST http://localhost:3000/add-comment
Content-Type: application/json

{
    "_id": "68caea19d590c898f438df70",
    "blog_author": "68caea19d590c898f438df70",
    "comment": "This is my test comment!"
}

###

### Add reply to comment (requires signin cookie)
POST http://localhost:3000/add-comment
Content-Type: application/json

{
    "_id": "68caea19d590c898f438df70",
    "blog_author": "68caea19d590c898f438df70",
    "comment": "This is a reply to the comment!",
    "replying_to": "68d109ddc003446133a09cea"
}

###

### Get comments for a blog
POST http://localhost:3000/get-blog-comments
Content-Type: application/json

{
    "blog_id": "BLOG_ID_HERE",
    "skip": 0
}

###

### Get replies for a comment
POST http://localhost:3000/get-replies
Content-Type: application/json

{
    "_id": "COMMENT_ID_HERE",
    "skip": 0
}

###

### Delete comment (admin only, requires signin cookie)
DELETE http://localhost:3000/delete-comment
Content-Type: application/json

{
    "_id": "COMMENT_ID_HERE"
}